### ISSUE TITLE
File missing?

### ISSUE THREAD

**Issue by marcoancona** [chakrit/gossip#1]
I think files are missing from the repo. 
You say

 Copy the file `pjsip/config_site.h` to `pjlib/include/pj/config_site.h

but there is not pjlib directory. Or I am missing something?

**Comment by chakrit** [comment]
@exeltior It's actually relative to the PJSIP source folder which actually is at `pjsip/source/pjlib` . Sorry for the late reply, I was on vacation.

Will update README later.

**Comment by sourabhletsgomo** [comment]
please help me out i am not getting how to compile this.
where to put config_site.h
