### ISSUE TITLE
SRV DNS records fail to resolve

### ISSUE THREAD

**Issue by pennomi** [chakrit/gossip#10]
AFAICT, PJSIP supports SRV DNS records, but Gossip doesn't. When I attempt to connect to my SIP server, I simply get a timeout.

What needs to be done so my app can connect properly? (I'm happy to submit a pull request once I have it figured out, but I'm not really sure where to start.)

**Comment by chakrit** [comment]
@pennomi Can you lookup on the PJSIP docs and see if I need to call any specific function or is there any specific configuration I should be doing?

The PJSUA API manual might be a good start: http://www.pjsip.org/docs/latest/pjsip/docs/html/group__PJSUA__LIB.htm

Also, you might be able to tweak the configure function to do something about it:
https://github.com/chakrit/gossip/blob/master/Gossip/GSUserAgent.m#L85

**Comment by pennomi** [comment]
I've also been on the mailing list. Here's the response I got:

> Hi Thane!
> 
> Have you configured some resolvers on PJSIP? If you don’t set them then it won’t do any SRV lookups. Get the resolver with `pjsip_endpt_get_resolver` and set some resolvers with `pj_dns_resolver_set_ns`.
> 
> Cheers,
> 
> Saúl Ibarra Corretgé
> AG Projects

Grepping through Gossip shows that it's not calling those functions anywhere. Is that a better place to start?

**Comment by pennomi** [comment]
Update from the mailing list with very specific directions:

> It’s very straightforward to use: just grab pointer to the `pjsip_endpoint` (there is a single ‘instance' of it), get the resolver and set some name servers, the rest will just work [...] You don’t need to do anything else, once name servers are in place PJSIP will automatically resolve SRV for you.

And from a source code comment:

> asynchronous DNS resolution will only be done when application calls `pjsip_endpt_create_resolver()`, configure the nameservers with `pj_dns_resolver_set_ns()`, and configure the SIP endpoint's DNS resolver with `pjsip_endpt_set_resolver()`. If these steps are not followed, the domain will be resolved with normal `pj_gethostbyname()` function.

**Comment by chakrit** [comment]
@pennomi Yep, that should be it. Add some resolver configuration calls into `[GSUserAgent configure:]` method and you should be good to go. When it comes to PJSIP, when it works it works really well as long as you get the right calls.

IIRC There is already and `pjsip_endpoint` being created in that method.

Otherwise I'll look into this maybe during this Saturday or Sunday.

**Comment by chakrit** [comment]
Just hardcode google's public DNS into it (or make an entry for configuring it in the configuration class.)

**Comment by pennomi** [comment]
Okay, good news. I've got this working on my app. I'll clean up my code and submit a pull request to you tonight or tomorrow.

As far as the pull request is concerned, would you prefer hardcoding Google's DNS or that I make it configurable (with Google as the default, of course)?

**Comment by chakrit** [comment]
Awesome : ) Either way is fine by me.

Having it configurable would be nice but IMO only a very small % of people would want to change it since it's just DNS.

**Comment by chakrit** [comment]
Merged #11
