### ISSUE TITLE
CocoaPods issue

### ISSUE THREAD

**Issue by oxcug** [chakrit/gossip#13]
Issue was reported here: https://github.com/CocoaPods/CocoaPods/issues/2368

I'll see if I cannot remedy the issue in the podfile in this repo (if I can grab the time) or if someone else want's to do it before me, feel free. Otherwise I'll try to get a merge request in soon.

**Comment by chakrit** [comment]
Whoops, let me fix that.

**Comment by chakrit** [comment]
I've fixed the podspec file as suggested but I have not fully tested it yet. I think it may not build because the PJSIP libs and headers might need to be included in the download (which I don't think is a good idea.) It is probably best to setup this up manually, for now.

A PR that would properly setup this repo to work the PJSIP pod that's already in the specs repo would be most welcome : )

**Comment by oxcug** [comment]
I've included PJSIP through another pod https://github.com/chebur/pjsip. It works fairly well, but I don't know how it'll work with both being imported using cocoapods. I'll test it later today and report back.

**Comment by oxcug** [comment]
There are some linker errors (as you predicted). The best solution I would think would be to either include pjsip or to set the search paths to assume they're using the pjsip pod. I've been tinkering with the search paths trying to get them to work from within the Pods project.

So far it's not working out too well. I'll keep cracking at it and see what happens and may be able to just edit the pod in this repo to automatically include pjsip so we don't have to deal with the linker problems. It'd be sweet if all it took to include pjsip and gossip were:

```
pod 'pjsip'
pod 'gossip', :git => 'https://github.com/chakrit/gossip.git'
```

**Comment by chakrit** [comment]
Yeah including PJSIP with the pod is the easiest way right now. If you can wait until the weekends I'll look into setting up proper CocoaPod dependency and see what I can do.

**Comment by Harold-D** [comment]
Hello Chakrit,

What is the status of the Gossip pod?
