### ISSUE TITLE
building error

### ISSUE THREAD

**Issue by sourabhletsgomo** [chakrit/gossip#3]
Please help me out i am stuck with the basic implementation i am not getting how to compile this.
It always says no such file or directory found when building ./build-pjsip.
Please help me out its very urgent

Thanking you in anticipation

**Comment by sourabhletsgomo** [comment]
i compiled but i am getting an error 
![screen shot 2013-07-01 at 1 21 28 pm](https://f.cloud.github.com/assets/4457503/728953/30792bb4-e223-11e2-8dd6-ed26073668c4.png)
please check dis out and respond me please sir

Thanking you in anticipation

**Comment by chakrit** [comment]
Not sure if I can help you here but please at least give some more info.

Can you show me how you are initializing PJSIP?
Also what version of Xcode / iOS are you using?

**Comment by sourabhletsgomo** [comment]
GSAccountConfiguration *account = [GSAccountConfiguration defaultConfiguration];
    account.address = @"ssssingh@sip.antisip.com";
    account.username = @"ssssingh";
    account.password = @"12345qaz";
    account.domain = @"sip.antisip.com";
    account.proxyServer = @"sip.antisip.com";
    [accounts addObject:account];
i used this account sir

i am using xcode 4.6.2 and ios 6.1

**Comment by chakrit** [comment]
What are you running? The example app ?

**Comment by sourabhletsgomo** [comment]
Yes , the example app , actually i have to make a sdk which includes wrapper for pjsip in objective c

**Comment by sourabhletsgomo** [comment]
earlier the app doesn't build because the build-pjsip command does not make files which are required as given in header search path,
Sir you have written awesome code which provides me way to think like this as i dont have to implement all features .

**Comment by chakrit** [comment]
Hmmm, that should be good to go. Not sure what happens there. If you replace the PJSIP binaries it might work. Try builds from https://github.com/chebur/pjsip

**Comment by sourabhletsgomo** [comment]
10:12:22.605 os_core_unix.c !pjlib 2.1-svn for POSIX initialized
10:12:22.611 sip_endpoint.c  .Creating endpoint instance...
10:12:22.615          pjlib  .select() I/O Queue created (0x20289144)
10:12:22.615 sip_endpoint.c  .Module "mod-msg-print" registered
10:12:22.616 sip_transport.  .Transport manager created.
10:12:22.617   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
10:12:24.691   pjsua_core.c  .pjsua version 2.1-svn for iPhone OS-6.0/arm/iOS-SDK-6.1 initialized
2013-07-02 10:12:25.989 GossipExample[1808:907] account id in gsaccount.m 0=-1
2013-07-02 10:12:29.453 GossipExample[1808:907] Disabling: speex/16000/1
2013-07-02 10:12:29.456 GossipExample[1808:907] Disabling: speex/8000/1
2013-07-02 10:12:29.458 GossipExample[1808:907] Disabling: speex/32000/1
2013-07-02 10:12:29.460 GossipExample[1808:907] Disabling: iLBC/8000/1
2013-07-02 10:12:29.462 GossipExample[1808:907] Disabling: GSM/8000/1
2013-07-02 10:12:29.463 GossipExample[1808:907] Disabling: PCMU/8000/1
2013-07-02 10:12:29.465 GossipExample[1808:907] Disabling: PCMA/8000/1
2013-07-02 10:12:39.488 GossipExample[1808:907] Gossip: dispatchRegistrationStarted(0, 1)
2013-07-02 10:12:39.492 GossipExample[1808:907] account id in gsaccount.m=0
2013-07-02 10:12:39.494 GossipExample[1808:907] account id in gsaccount.m=0
10:12:40.007    pjsua_acc.c !....IP address change detected for account 0 (192.168.5.54:51573 --> 220.227.69.18:51573). Updating registration (using method 2)
2013-07-02 10:12:40.800 GossipExample[1808:4003] Gossip: dispatchRegistrationStarted(0, 1)
2013-07-02 10:12:40.803 GossipExample[1808:4003] account id in gsaccount.m=0
2013-07-02 10:12:40.805 GossipExample[1808:4003] account id in gsaccount.m=0
10:12:41.226    pjsua_acc.c  ....sip:ssssingh@sip.antisip.com: registration success, status=200 (OK), will re-register in 300 seconds
2013-07-02 10:12:43.052 GossipExample[1808:4003] Gossip: dispatchRegistrationState(0)
2013-07-02 10:13:06.624 GossipExample[1808:907] here useraddress=ssssingh@sip.antisip.com
2013-07-02 10:13:08.401 GossipExample[1808:907] Gossip: ringbackWithSoundNamed: /var/mobile/Applications/80BDAA7A-50BB-4E1A-A587-F61D3E7CAA0D/GossipExample.app/ringtone.wav
2013-07-02 10:13:08.403 GossipExample[1808:907] FILENAME=ringtone.wav
10:13:08.405    pjsua_aud.c !.Unable to create playlist: Not found (PJ_ENOTFOUND) [status=70006]
2013-07-02 10:13:09.681 GossipExample[1808:907] Gossip: Error Domain=pjsip.org Code=240006 "Not found (PJ_ENOTFOUND)" UserInfo=0x1f5c2810 {pj_status_t=70006, PJSIP_ERRNO_FORM_SIP_STATUS=240006, NSLocalizedDescription=Not found (PJ_ENOTFOUND)}
2013-07-02 10:13:10.694 GossipExample[1808:907] accountid=0, 

after this that trap appears i.e  png image what i sent you earlier

**Comment by sourabhletsgomo** [comment]
please have a look sir because this is what we are searching for and i will be highly obliged to you

**Comment by chakrit** [comment]
Seems you are trying to use G.729, it tends to have a lot of problems. If you can avoid it for the time being, it will probably work better.

The G.729 patch is having a problem right now, please try without it for the time being.

I'm patching the code to use an alternative builds of G.729 but not guarantee on when i will be done with it.

**Comment by sourabhletsgomo** [comment]
Ok means you are going to change the codec from g729 to anything else

**Comment by chakrit** [comment]
No I still need it but there were lots of problems with it so I'm looking to switch to https://github.com/lemenkov/bcg729 for it.

**Comment by sourabhletsgomo** [comment]
sir can we use g711 codec because in many applications i have seen g711

**Comment by chakrit** [comment]
@sourabhletsgomo then it's probably best to build pjsip without the  G.729 patch.

If you check the `build-pjsip` scripts there were some lines that runs `git apply` to patch the codebase, if you remove those lines and re-build the binaries it might solve the problem you have now.

Give it a go.

**Comment by sourabhletsgomo** [comment]
when i try to build build-pjsip then 
/Users/letsgomo028/Desktop/imp/gossip-master/pjsip/build-pjsip: line 6: cd: source: No such file or directory

In directory: /Users/letsgomo028
fatal: Not a git repository (or any of the parent directories): .git

Will do inside the pjsip source folder:
    GIT CLEAN -XDF
    GIT RESET --hard HEAD

CTRL+C to cancel now or be _VERY_ sure you want to proceed by pressing any key.

**Comment by chakrit** [comment]
ah  you need to check out git submodules as well.

`git submodule update --init --recursive`

**Comment by sourabhletsgomo** [comment]
![screen shot 2013-07-02 at 10 41 32 am](https://f.cloud.github.com/assets/4457503/734681/e72787a4-e2d5-11e2-87fb-a5f9649fee8c.png)
when i extracted your project zip then i didnt find git submodules

**Comment by chakrit** [comment]
Extract zip?! Please clone it from github using the `git` command.

**Comment by sourabhletsgomo** [comment]
``` sh
#!/bin/sh

# A script to compile for iOS device.

pushd .
cd source

# clean pjsip folder
echo ""
echo In directory: `pwd`
git clean -xdn
echo ""
echo "Will do inside the pjsip source folder:"
echo "    GIT CLEAN -XDF"
echo "    GIT RESET --hard HEAD"
echo ""
echo "CTRL+C to cancel now or be _VERY_ sure you want to proceed by pressing any key."
echo ""
read
git clean -xdf
git reset --hard HEAD

# configure PJSIP builds
export ARCH="-arch armv7"

# apply G729 patch and copy all needed stuff into PJSIP source tree.
git apply --stat ../g729/enable_g729.patch
git apply ../g729/enable_g729.patch
cp -iv ../g729/g729a_include/*.h third_party/
cp ../g729/pj_g729.h third_party/
cp ../g729/pj_g729.c pjmedia/src/pjmedia-codec/g729.c # so it compiles as part of pjsip

mkdir -p third_party/lib
cp ../g729/libg729a.a third_party/lib/libg729codec-arm-apple-darwin10.a

# ... and build
./configure-iphone | tee ../configure.log
make dep | tee ../make-dep.log
make | tee ../make.log
popd

./copy-libs
./show-info
```

which line i have to remove

**Comment by chakrit** [comment]
``` sh
# apply G729 patch and copy all needed stuff into PJSIP source tree.
git apply --stat ../g729/enable_g729.patch
git apply ../g729/enable_g729.patch
cp -iv ../g729/g729a_include/*.h third_party/
cp ../g729/pj_g729.h third_party/
cp ../g729/pj_g729.c pjmedia/src/pjmedia-codec/g729.c # so it compiles as part of pjsip

mkdir -p third_party/lib
cp ../g729/libg729a.a third_party/lib/libg729codec-arm-apple-darwin10.a
```

IIRC

**Comment by sourabhletsgomo** [comment]
after doing this pj/config_site.h file not found error while building ,
but i had compiled earlier the pjsip and i had given path to my compiled file in header search path

**Comment by sourabhletsgomo** [comment]
sir then also the same error

**Comment by chakrit** [comment]
Remove these two lines:

``` sh
git clean -xdf
git reset --hard HEAD
```

Copy `config_site.h` from `pjsip/config_site.h` to `pjsip/source/pjlib/include/pj`.

Then try again.

**Comment by sourabhletsgomo** [comment]
~/Desktop/sssourabh/gossip/pjsip ~/Desktop/sssourabh/gossip/pjsip
when i try to run build-pjsip the it says this and i deleted all you said
In directory: /Users/letsgomo028/Desktop/sssourabh/gossip/pjsip/source

Will do inside the pjsip source folder:
    GIT CLEAN -XDF
    GIT RESET --hard HEAD

CTRL+C to cancel now or be _VERY_ sure you want to proceed by pressing any key.

**Comment by sourabhletsgomo** [comment]
please dont mind sir but pls you check that call is going or not

**Comment by chakrit** [comment]
you mean you want to check if the call is successful?

**Comment by sourabhletsgomo** [comment]
Yes sir i want you to call at your own level or me at sssourabh@sip.antip.com
one thing more sir in GSConfiguration.m  
// TODO: Probably better to do via class_copyPropertyList.
    replica.logLevel = self.logLevel;
    replica.consoleLogLevel = self.consoleLogLevel;
    replica.transportType = self.transportType;

```
replica.clockRate = self.clockRate;
replica.soundClockRate = self.soundClockRate;
replica.volumeScale = self.volumeScale;

replica.account = [self.account copy]; 
```

there is no config for media or codec

**Comment by chakrit** [comment]
I cannot do that right now.

Please use something like https://www.counterpath.com/x-lite.html to test it.

Run X-lite on your machine signed in to another SIP account on the same server.
Then run the test app on the phone and dial it.

---

For media codecs, PJSIP doesn't let you configure it that way. You'll just have to adjust the codec priorities so it picks the one you want first. i.e. set codecs you don't want to 0 priority.

**Comment by sourabhletsgomo** [comment]
sir actually when i call on the desired address it gives that trap error

**Comment by chakrit** [comment]
Play with the codec priorities. See if it's specific to that codec.

Can't help you more than that now.

You might have better luck working with the PJSIP guys directly.

**Comment by sourabhletsgomo** [comment]
thank you sir thanks for help , but if you get time to test call then please make it and give your feed back

**Comment by sourabhletsgomo** [comment]
@hlung -- please check this as i am geting error while running it and i am not able to figure it out

**Comment by hlung** [comment]
@sourabhletsgomo what error are you getting? did you manage to compile gossip?

**Comment by sourabhletsgomo** [comment]
Yes sir but when i make a call then pjsua_call_media_init TRAP and applicaton crashes as i discussed above

**Comment by sourabhletsgomo** [comment]
but to compile it i had used replaced the path in header search paths in gossip because when i give ./build-pjsip it do not create anything

**Comment by hlung** [comment]
What is the output when you run ./build-pjsip ?

**Comment by sourabhletsgomo** [comment]
Last login: Wed Jul  3 12:52:11 on ttys002
Letsgomos-Mac-mini-3:~ letsgomo028$ cd /Users/letsgomo028/Desktop/sssourabh/gossip/pjsip 
Letsgomos-Mac-mini-3:pjsip letsgomo028$ ./build-pjsip
~/Desktop/sssourabh/gossip/pjsip ~/Desktop/sssourabh/gossip/pjsip

In directory: /Users/letsgomo028/Desktop/sssourabh/gossip/pjsip/source

Will do inside the pjsip source folder:
    GIT CLEAN -XDF
    GIT RESET --hard HEAD

CTRL+C to cancel now or be _VERY_ sure you want to proceed by pressing any key.

c
./build-pjsip: line 27: ./configure-iphone: No such file or directory
make: **\* No rule to make target `dep'.  Stop.
make: **\* No targets specified and no makefile found.  Stop.
~/Desktop/sssourabh/gossip/pjsip

### includes

### arch

Letsgomos-Mac-mini-3:pjsip letsgomo028$

**Comment by hlung** [comment]
Your "configure-iphone" file is missing. And it's in pjsip submodule.
Did you run `git submodule init` then `git submodule update` ?

**Comment by sourabhletsgomo** [comment]
no but where is pjsip submodule

**Comment by hlung** [comment]
It's already configured in the gossip repository. Just clone the repo, then run `git submodule init` then `git submodule update` dude.

**Comment by sourabhletsgomo** [comment]
after cloning the gossip from url https://github.com/chakrit/gossip.git i have to run this command

**Comment by hlung** [comment]
of course

**Comment by sourabhletsgomo** [comment]
i got it sir thanks for your resoponse .
thank you very much sir

**Comment by hlung** [comment]
no problem sir

**Comment by sourabhletsgomo** [comment]
i had done that and i build the ./build-pjsip after it is complete i had made a call and it gives error  after this also the same error , i am not able to figure it out . please help me
![screen shot 2013-07-03 at 1 30 30 pm](https://f.cloud.github.com/assets/4457503/741761/cf5fcfd2-e3b6-11e2-983e-96ca964960ac.png)

**Comment by sourabhletsgomo** [comment]
Please help me @hlung

**Comment by hlung** [comment]
I have no idea on this one sorry.

**Comment by sourabhletsgomo** [comment]
where should is ask any sip guys u know u pls forward there id i will ask them , its urgent please sir

**Comment by DAOCUONG** [comment]
I have the same problem dont know why it was crashed when making call and received call, any one can give a hint?

**Comment by amozheyko** [comment]
And I have the same problem(((
It crashes when I try to make a call.. iOS 7

**Comment by wongshandev** [comment]
any friend here?It crashes when I try to make a call.. iOS 7,any friend help me? @chakrit @hlung ,
and i try download the last pjsip project from http://www.pjsip.org/ (PJSIP version 2.2.1) ,and have same problem!

**Comment by chakrit** [comment]
@DAOCUONG @MADzone @wongshandev Can you all give me some sample codes / log output or whatever you guys have? I'll investigate and get this thing up to date during the end of the month or around that time.

G.729 will not be supported though. It will takes too much time with all the arcane and indecipherable compilation and linking issues.

**Comment by wongshandev** [comment]
@chakrit @hlung  tks sir,log:

14:20:25.498 os_core_unix.c !pjlib 2.1-svn for POSIX initialized
14:20:25.503 sip_endpoint.c  .Creating endpoint instance...
14:20:25.506          pjlib  .select() I/O Queue created (0x183c373c)
14:20:25.506 sip_endpoint.c  .Module "mod-msg-print" registered
14:20:25.506 sip_transport.  .Transport manager created.
14:20:25.506   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
14:20:25.536   pjsua_core.c  .pjsua version 2.1-svn for iPhone OS-7.1.1/arm/iOS-SDK-6.1 initialized
2014-04-28 14:20:27.055 GossipExample[1036:60b] Gossip: dispatchRegistrationStarted(0, 1)
14:20:30.233    pjsua_acc.c !....IP address change detected for account 0 (192.168.1.59:57431 --> 117.136.32.7:44666). Updating registration (using method 2)
2014-04-28 14:20:30.234 GossipExample[1036:4403] Gossip: dispatchRegistrationStarted(0, 1)
14:20:31.897    pjsua_acc.c  ....sip:18682312707@117.135.131.240:8060: registration success, status=200 (OK), will re-register in 300 seconds
2014-04-28 14:20:31.897 GossipExample[1036:4403] Gossip: dispatchRegistrationState(0)
2014-04-28 14:21:47.837 GossipExample[1036:60b] Gossip: ringbackWithSoundNamed: /var/mobile/Applications/9C32697C-2875-4D47-998E-2C0E3BA41991/GossipExample.app/ringtone.wav

![2014-04-28 15 32 24](https://cloud.githubusercontent.com/assets/1710333/2814341/7b4bbd66-cea7-11e3-9571-2984344a5cbe.png)

**Comment by wongshandev** [comment]
my friend,pls edit file(build-pjsip) :export ARCH="-arch armv7"  -> export ARCH="-arch armv7 -arch armv7s", A7 use armv7s ! @chakrit @hlung :8ball:

**Comment by chakrit** [comment]
I have since updated all the build scripts to use a more robust approach now. Also included in the repo is a fat binary that should work for all architecture so you guys won't have to build it yourself.

Gonna close this issue for now. Open a new issue if you still have trouble getting GOSSIP to compile with the specific error you get so I can debug them.
