### ISSUE TITLE
G.729 and PJSIP

### ISSUE THREAD

**Issue by mohitsud** [chakrit/gossip#6]
Hi Their,

 I am having an issue using your G.729 patch when compiling PJSIP. Could you provide more instructions on how to get this to work?

Thank you.

**Comment by sourabhletsgomo** [comment]
I think g729 did not work with pjsip

**Comment by mohitsud** [comment]
Thanks for the reply.

This tutorial says it  should work:
http://trac.pjsip.org/repos/wiki/Intel_IPP_Codecs

But I am not sure how to tie the two together.

**Comment by chakrit** [comment]
@mohitsud that requires the Intel IPP codecs. You need to pay Intel to use it AFAIK.

**Comment by sourabhletsgomo** [comment]
oh yes i remember just now, i and my team had made a framework for ios
based on pjsip
yes you are correct we also face he same problem

**Comment by mohitsud** [comment]
Hi there,

Thank you for the reply. I am happy to pay for the G.729 codec, but I am not sure how to compile PJSIP with it . Do you have any suggestions?

**Comment by chakrit** [comment]
Hmm, just check the PJSIP docs. Also the script to build the binaries is https://github.com/chakrit/gossip/blob/master/pjsip/build-pjsip You might want to look at them and adjust.

**Comment by chakrit** [comment]
Will take a look and update you with specifics if i have time.

**Comment by sourabhletsgomo** [comment]
@mohit - actually we continued with other codecs as per our requirement .
                   If you do that please update me if you can

**Comment by mohitsud** [comment]
Hi Chakrit,

If you could please provide specifics that would be most appreciated.

Thank you.

**Comment by chakrit** [comment]
Due to time constraints I don't think I will be able to support the G.729 patch in anyway from now. I have since removed all the related files. You can find my original fork at http://github.com/oozou/gossip if you still need them (or just go back in time using git)

G.729 seems to be a patent-ridden codec and there are barely any working implementation available let alone a patch that would integrate the implementation into PJSIP. So it is really out of my power to continue supporting it.

**Comment by saravnandm** [comment]
Refer my git contribution.https://github.com/saravanandm/pjsip-g729codec  It works well, tested with ios app.

**Comment by meghaParmar** [comment]
Hi Saravandm,
I downloaded your patches, but unable to configure it with my code. Please give steps to use them.

**Comment by dmsaravanan** [comment]
What is the issue? Did you follow the patches(steps)? for details create an issue in my repo https://github.com/saravanandm/pjsip-g729codec

**Comment by meghaParmar** [comment]
Hi Sarvanandm,
Thanks for reply and patch.
I am little-bit confuse with integrate your patch and my source. It's look like you clone pjsip source from git. 
It will be appreciable if you provide me original source repo of pjsip or any link in which this patch works.

**Comment by meghaParmar** [comment]
I think this https://github.com/chakrit/pjsip is your repo but will this work with latest source of pjsip if follow all steps.
Please help me out.

**Comment by dmsaravanan** [comment]
I think https://github.com/chakrit/pjsip  source should work with my patches i have tested with pjsip2.0. More than 2 years back.

**Comment by dmsaravanan** [comment]
Soon will update my patches for latest version of pjsip. If you need anything further command it on my repo.

**Comment by meghaParmar** [comment]
Thanks for your continuous effort. I am trying to apply your repo in my project. I will reply you here if got any problem with that. 
Your help is really appreciable.

**Comment by saravnandm** [comment]
Patch update for pjsip 2.5 https://github.com/saravanandm/pjsip2.5-g729codec

**Comment by meghaParmar** [comment]
Hi Sarvanandam,
I followed your link and applied patches , after that I tried to build using "make dep"

This command throws following error:
`ld: library not found for -lg729codec-armv7-apple-darwin_ios
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [../bin/pjmedia-test-armv7-apple-darwin_ios] Error 1
make[1]: *** [pjmedia-test-armv7-apple-darwin_ios] Error 2
make: *** [all] Error 1`

This procedure I followed inside PJSIP 2.5 folder,
Do we need to build G729 folder seperately?

Thanks.
