### ISSUE TITLE
Can't connect to getonsip.com

### ISSUE THREAD

**Issue by saurabhsharma** [chakrit/gossip#7]
I compiled this successfully thanks!!
But I am not able to connect with getonsip.com. 
Using these - 

account.address = @"saurabhsharma@getonsip.com";
account.username = @"getonsip_saurabhsharma";
account.password = @"tWEyNkVMEfFiw66z";
account.domain = @"getonsip.com";
account.proxyServer = @"sip.onsip.com";

Any idea what may be wrong?

**Comment by saurabhsharma** [comment]
Also tried sip2sip.com account.. but no luck.. definitely something wrong with code.. ?

**Comment by chakrit** [comment]
Can you paste some log message? There should be some output from PJSIP. Not sure if the default config logs everything tho.

**Comment by saurabhsharma** [comment]
Here is console log - 

11:57:27.616 os_core_unix.c !pjlib 2.1-svn for POSIX initialized
11:57:27.628 sip_endpoint.c  .Creating endpoint instance...
11:57:27.636          pjlib  .select() I/O Queue created (0x1f9d1334)
11:57:27.637 sip_endpoint.c  .Module "mod-msg-print" registered
11:57:27.637 sip_transport.  .Transport manager created.
11:57:27.639   pjsua_core.c  .PJSUA state changed: NULL --> CREATED
11:57:27.714   pjsua_core.c  .pjsua version 2.1-svn for iPhone OS-6.1.3/arm/iOS-SDK-6.1 initialized
2014-03-04 11:57:28.458 GossipExample[312:907] Gossip: dispatchRegistrationStarted(0, 1)
11:58:00.458    pjsua_acc.c !...SIP registration failed, status=408 (Request Timeout)
2014-03-04 11:58:00.458 GossipExample[312:4203] Gossip: dispatchRegistrationState(0)
2014-03-04 11:58:07.883 GossipExample[312:4203] Gossip: dispatchRegistrationStarted(0, 1)
11:58:39.884    pjsua_acc.c  ...SIP registration failed, status=408 (Request Timeout)
2014-03-04 11:58:39.885 GossipExample[312:4203] Gossip: dispatchRegistrationState(0)
2014-03-04 11:58:47.207 GossipExample[312:907] Gossip: dispatchRegistrationStarted(0, 1)
11:59:19.208    pjsua_acc.c  ...SIP registration failed, status=408 (Request Timeout)
2014-03-04 11:59:19.209 GossipExample[312:4203] Gossip: dispatchRegistrationState(0)

**Comment by chakrit** [comment]
```
11:58:00.458 pjsua_acc.c !...SIP registration failed, status=408 (Request Timeout)
```

Are you sure you have put in the right settings?
Can you try with another SIP program on your local machine and see if the setting works?

**Comment by chakrit** [comment]
Looks like it cannot find the server there or there's some kind of firewall between you and the SIP server.

**Comment by chakrit** [comment]
Closing due to no input from the OP.

**Comment by othmaan** [comment]
Same here. I cannot connect to SIP server.

**Comment by othmaan** [comment]
Update: sip2sip works for me, onsip won't work

**Comment by entangledloops** [comment]
You misspelled the proxy server address. Should be `sip.getonsip.com`, you have `sip.onsip.com`.
