### ISSUE TITLE
DTMF digits ?

### ISSUE THREAD

**Issue by muzammil-hussain** [chakrit/gossip#8]
How to send DTMF commands via gosip

**Comment by chakrit** [comment]
Hmmm :/ Is that supported by PJSIP ?

If you can lookup the right PJSIP call I might be able to add a nice API for it.

**Comment by muzammil-hussain** [comment]
Yes PJSIp does support it. Followign is pjsip call
pj_status_t     pjsua_call_dial_dtmf (pjsua_call_id call_id, const pj_str_t *digits)

**Comment by chakrit** [comment]
@muzammil-hussain I have added a `[GSCall sendDTMFDigits:(NSString *)]` method. There are also some changes in the latest commit. Can you try and let me know if this works for you?

**Comment by chakrit** [comment]
Gonna close this for now, feel free to reopen if this does not work.
